//
//  CropModels.swift
//  MotorImages
//
//  Created by iris on 05/07/20.
//  Copyright (c) 2020 iris. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Crop
{
  // MARK: Use cases
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
		var imagenRecibida: UIImage
		var imagenRecibidaCG : CGImage
    }
    struct ViewModel
    {
		var imagenRecibida: UIImage
		var imagenRecibidaCG : CGImage

    }
  }
	enum  CropImage
	{
		struct Request
		{
			var originalImage : UIImage
			var originalImageCG : CGImage
			var cutFrame : CGRect
		}
		struct Response
		{
		}
		struct ViewModel
		{
		}
	}
}
