//
//  CropRouter.swift
//  MotorImages
//
//  Created by iris on 05/07/20.
//  Copyright (c) 2020 iris. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CropRoutingLogic
{
  func routeToDocumentViewController()
}

protocol CropDataPassing
{
  var dataStore: CropDataStore? { get }
}

class CropRouter: NSObject, CropRoutingLogic, CropDataPassing
{
	weak var viewController: CropViewController?
	var dataStore: CropDataStore?
  // MARK: Routing
  
  func routeToDocumentViewController()
  {
	if let destinationVC = viewController?.navigationController?.viewControllers[0] as? DocumentViewController{
		var destinationDS = destinationVC.router!.dataStore!
		passDataToSomewhere(source: dataStore!, destination: &destinationDS)
		viewController?.navigationController?.popViewController(animated: false)
	}
  }

	// MARK: Navigation	var NewImage : UIImage?

  
  // MARK: Passing data
  
  func passDataToSomewhere(source: CropDataStore, destination: inout DocumentDataStore)
  {
	destination.croppedImage = source.croppedImage
	}
}
