//
//  DocumentInteractor.swift
//  MotorImages
//
//  Created by iris on 05/07/20.
//  Copyright (c) 2020 iris. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DocumentBusinessLogic{
	func saveOriginalImage(request: Documents.cropImageSend.Request)
	func fetchCropped()
}

protocol DocumentDataStore
{
	var originalImage: UIImage? { get set }
	var originalImageCG : CGImage? {get set}
	var croppedImage : Data? { get set }
}

class DocumentInteractor: DocumentBusinessLogic, DocumentDataStore {
	var originalImageCG: CGImage?
	var croppedImage: Data?
	
	func fetchCropped() {
		if let croppedImg = croppedImage{
			let response = Documents.fecthCropped.Response(cropImage: croppedImg)
			presenter?.croppedFetched(response: response)
		}
	}
		
	var originalImage: UIImage?
	var presenter : DocumentPresentationLogic?
  
  // MARK: Do something

	func saveOriginalImage(request: Documents.cropImageSend.Request) {
		originalImage = request.originalImage
		originalImageCG = request.originalImageCG
	}
	
}
