//
//  DocumentPresenter.swift
//  MotorImages
//
//  Created by iris on 05/07/20.
//  Copyright (c) 2020 iris. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DocumentPresentationLogic
{
	func viewForCrop(response:Documents.cropImageSend.Response)
	func croppedFetched(response: Documents.fecthCropped.Response )
}

class DocumentPresenter: DocumentPresentationLogic
{
	func croppedFetched(response: Documents.fecthCropped.Response) {
		viewController?.croppedFinished()
	}
	
	func viewForCrop(response: Documents.cropImageSend.Response) {
		let viewModel = Documents.cropImageSend.ViewModel()
		viewController?.displayCropView(viewModel: viewModel)
	}
	
  weak var viewController: DocumentViewControllerDelegate?
  
  // MARK: Do something
  
}
