//
//  DocumentModels.swift
//  MotorImages
//
//  Created by iris on 05/07/20.
//  Copyright (c) 2020 iris. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public enum Documents
{
	enum StartProcess {
		struct Request {
			var title : String
		}
		struct Response {
		}
		struct ViewModel {
		}
	}
	enum cropImageSend {
		struct Request {
			var originalImage : UIImage
			var originalImageCG : CGImage
		}
		struct Response {
		}
		struct ViewModel {
		}
	}
	enum fecthCropped {
		struct Request {
		}
		struct Response {
			var cropImage : Data
		}
		struct ViewModel {
		}
	}
}
